### ISSUE TITLE
Octokit warning when indicates failure

### ISSUE THREAD

**Issue by aroller** [cycjimmy/semantic-release-action#20] opened 2020-01-28 14:49 UTC
**Describe the bug**
When running the semantic release action, a warning is posted:

```
Run cycjimmy/semantic-release-action@v2.1.3
added 1 packages in 0.393s

##[error]npm WARN marked-terminal@3.3.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 || ^0.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN @octokit/plugin-rest-endpoint-methods@2.1.0 requires a peer of @octokit/core@>=2.1.2 but none is installed. You must install peer dependencies yourself.
```
A popup at the end of the run indicates failure.

**Workflow**
```
name: Release
on: 
  push:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.1.3
        id: semantic   # `id` for output variables
        with:
          semantic_version: 16.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

More errors appear when not specifying a semantic_version. This combination of action and semantic version produces the fewest warnings I found.

**Expected behavior**
No warning

**Additional context**
![image](https://user-images.githubusercontent.com/312949/73274378-57153c80-419a-11ea-9a7d-a0eb6ad927b3.png)

**Comment by cycjimmy** [comment] 2020-01-28 15:23
Thanks for your issue. 

The warning comes from the installation of semantic-release. An issue has been raised, but not resolved. https://github.com/semantic-release/semantic-release/issues/1429

**Comment by aroller** [comment] 2020-01-28 17:12
This solves it in the meantime.   Share it if you please, but understandable if you wish to wait for the more appropriate fix.  Please close otherwise. 
![image](https://user-images.githubusercontent.com/312949/73287452-24753f00-41ae-11ea-9d79-a6d2d9eab164.png)

**Comment by cycjimmy** [comment] 2020-01-29 03:35
@aroller Thank you for your contribution. But I don't think it should be fixed in this repository temporarily. The warning recently started appearing after `semantic-release@16.0.1` (#14). Since the warning does not affect the existing functions of this action, I think waiting for upstream dependencies to fix the problem is a better choice. And I will consider your suggestions at the right time.

**Comment by cycjimmy** [comment] 2020-02-07 16:06
It seems the latest version of `semantic-release` has fixed the issue.

**Closed by cycjimmy** 2020-02-07 16:06 UTC
