### ISSUE TITLE
Error: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by blackfalcon** [cycjimmy/semantic-release-action#69] opened 2021-06-16 08:22 UTC
**Describe the bug**

As of midnight 6/16 my repos started failing and the only error report is this.

```shell
25s
Run cycjimmy/semantic-release-action@v2
  with:
  env:
    GITHUB_TOKEN: ***
    NPM_TOKEN: ***
added 2 packages in 0.271s


Error: SyntaxError: Unexpected token '.'
```

**Workflow**

No code changes were made other than updating packages. Updates were pushed with a `fix` prefix and the build failed with this reply. 

**Expected behavior**

Builds pass and the package is released. 

**Additional context**

https://github.com/AlaskaAirlines/auro-table/commit/091a4384638dbba16d37b88fc8378826437629d6

**Comment by dimaturishchev** [comment] 2021-06-16 09:09
Our builds suddenly failed today with the same error. No packages were updated, only minor changes in the source code.

**Comment by denouche** [comment] 2021-06-16 09:16
Same problem here!

**Comment by dimaturishchev** [comment] 2021-06-16 09:23
https://github.com/markedjs/marked/pull/2109/files should be fixed soon

**Comment by dimaturishchev** [comment] 2021-06-16 09:26
@blackfalcon as a temporary solution, you can downgrade your semantic-release version OR switch to Node 14 or later

**Comment by denouche** [comment] 2021-06-16 09:29
Downgrading the semantic-release-action is not working @dimaturishchev , I set the version to 116647291d9b7bef1f5a4315deedd3f46ed4218b and I also have the problem

**Comment by dimaturishchev** [comment] 2021-06-16 09:32
@denouche I fixed my build by using
```
with:
  semantic_version: 17.3.3
```
parameter for semantic-release

**Comment by denouche** [comment] 2021-06-16 09:53
it works with this version of semantic-release, thank you @dimaturishchev !!

**Comment by portellaa** [comment] 2021-06-16 10:03
i confirm @denouche 17.3.7 also works. 👍

**Comment by execution** [comment] 2021-06-16 10:34
i confirm  17.3.7 also works too. 👍

**Comment by cyberhck** [comment] 2021-06-16 11:02
@execution good to know you're using semantic-release as well, are you also using at company? When I did that talk I didn't get much traction :laughing:

**Comment by blackfalcon** [comment] 2021-06-16 15:24
@dimaturishchev THIS is how OSS is supposed to work. Thanks to everyone who jumped in on this issue.

**Comment by dargmuesli** [comment] 2021-06-16 18:42
For me, builds pass again now without manual changes.

**Comment by ifndefdeadmau5** [comment] 2021-06-17 01:40
@dargmuesli yea, it's very weird. I thought semantic-release-action had new release but looks like not

**Comment by cycjimmy** [comment] 2021-06-24 01:32
This seems to be a problem caused by the previous version of the dependent library `marked` which has now been resolved.

**Closed by cycjimmy** 2021-06-24 01:32 UTC
