### ISSUE TITLE
[TODAY] Github Actions - Genera an error

### ISSUE THREAD

**Issue by okarook** [cycjimmy/semantic-release-action#143] opened 2023-01-06 21:50 UTC
**Describe the bug**
My Github action has an error
This error occurred today, yesterday everything was fine

![](https://user-images.githubusercontent.com/4731245/211103021-0c0c0280-9770-41c2-88a3-d56e13479309.png)

**Workflow**
This is my action

```
name: Semantic Release
on:
  push:
    branches: [ production ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0

      - name: Install Dependencies
        run: yarn install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic  
        with:
          branch: production
        env:
          GITHUB_TOKEN: ${{ secrets.XXXX }}
  
```

**Expected behavior**
This action should work in my GitHub

**Additional context**
I have seen that the [semantic-release](https://github.com/semantic-release/semantic-release) package a few minutes ago updated to a new version.

**Comment by MikeMcC399** [comment] 2023-01-08 09:48
@okarook

I'm also seeing the error using `cycjimmy/semantic-release-action@v2`. There was a release of [semantic-release v20.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0) on Jan 6, 2023. According to the release notes it contains breaking changes related to ESM-only and minimum Node.js 18.

If possible it is probably best just to update to using `cycjimmy/semantic-release-action@v3` which also gets rid of some deprecation warnings.

## Upgrade to `cycjimmy/semantic-release-action@v3`

Upgrading to v3 of `cycjimmy/semantic-release-action` without specifying [semantic_version](https://github.com/cycjimmy/semantic-release-action#semantic_version) resolves this issue. It seems that this is because a default version is specified in the action:

https://github.com/cycjimmy/semantic-release-action/blob/56bb7f907a74ca490c095c9584d4091b3ab5905f/package.json#L28

## `semantic_version`

Adding the following works around the issue when using the previous v2 version `cycjimmy/semantic-release-action@v2`:

```yml
          semantic_version: 19
```

This is according to the README section for the parameter [semantic_version](https://github.com/cycjimmy/semantic-release-action#semantic_version) where it says:

"It is recommended to manually specify a version of semantic-release to prevent errors caused during the official semantic-release upgrade"

After making the change the log files then show:

```text
[semantic-release] › ℹ  Running semantic-release version 19.0.5
```

instead of:

```text
Error: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js
```

**Comment by cycjimmy** [comment] 2023-01-09 05:53
This is caused by BREAKING CHANGES in semantic-release v20. You can temporarily lock the version to v19 to solve this problem.

```yaml
with:
  semantic_version: 19
```

https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0

**Comment by MikeMcC399** [comment] 2023-01-09 06:23
@cycjimmy 

Are you planning any new release of [cycjimmy/semantic-release-action](https://github.com/cycjimmy/semantic-release-action/) to support v20 of [semantic-release/semantic-release](https://github.com/semantic-release/semantic-release/)?

**Comment by cycjimmy** [comment] 2023-01-09 07:16
Yes. But this action uses a Javascript container. Currently, the only Javascript containers available on Github are `node12` and `node16`, and semantic-release v20 requires node18 or higher. So we may have to wait a little longer.


> @cycjimmy
> 
> Are you planning any new release of [cycjimmy/semantic-release-action](https://github.com/cycjimmy/semantic-release-action/) to support v20 of [semantic-release/semantic-release](https://github.com/semantic-release/semantic-release/)?

**Comment by MikeMcC399** [comment] 2023-01-09 07:36
@cycjimmy

> Yes. But this action uses a Javascript container. Currently, the only Javascript containers available on Github are node12 and node16, and semantic-release v20 requires node18 or higher. 

Thank you for pointing out this compatibility issue!

Issue https://github.com/actions/runner/issues/2255 requesting support for `node18` was closed with the hint that the next supported version may be `node20`.

According to https://github.com/nodejs/release#release-schedule Node.js 20 is planned for release on 2023-04-18

> So we may have to wait a little longer.

You are right! Probably this means quite a few months:
Release of Node.js 20 > Support on GitHub

**Comment by okarook** [comment] 2023-01-10 14:55
Thanks, I don't have the version on the GitHub Action  ✌️

**Comment by MikeMcC399** [comment] 2023-01-10 17:12
@okarook

Please let us know if the suggested fixes (add

```yaml
    with:
      semantic_version: 19
```

or update to @v3, or add the version together with updating to @v3) fixed the issue for you.

**Comment by buehler** [comment] 2023-01-17 08:39
Would it be an option to move to a docker based github action? Then you can adjust your node version quite easily. Or are there any implications that I don't see?

**Comment by MikeMcC399** [comment] 2023-02-07 18:25
@okarook 

If you are now back up and running, then I suggest to close this issue.

[README: Semantic version](https://github.com/cycjimmy/semantic-release-action/blob/main/README.md#semantic_version) has been updated to give the correct advice based on the discussions here in this issue.

Thanks for reporting this issue. It was very useful to me!

**Closed** 2023-02-08 22:45 UTC

**Comment by MikeMcC399** [comment] 2023-07-24 13:59
@cycjimmy 

In case you hadn't seen it
https://github.com/actions/runner/discussions/2704
announced the plan to support `node20` for GitHub JavaScript Actions.

No date yet.
